# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: docker-build

on:
  release:
    types: [created]

jobs:
  deploy_docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker build and push
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: jumo20201124/jumo20201124
        tag_with_ref: true
