name: release

on:
  release:
    types: [created]

jobs:
  deploy_docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker build and push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: kapture/kapture-localization
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        tag_names: true
    - name: docker build and push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: kapture/kapture-localization
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        tags: "latest"


