# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: docker-build

on:
  release:
    types: [created]

jobs:
  deploy_docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker build and push
      uses: elgohr/Publish-Docker-Github-Action@master
      pre: echo ::save-state name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      with:
        name: jumo20201124/jumo20201124
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ env.STATE_RELEASE_VERSION }}"
